configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/data.smk"
include: "rules/model.smk"
include: "rules/visualization.smk"


MODEL_NAMES = [k for k in config.get("models", {}) if k != "default"]
EXPERIMENTS = config.get("experiments", [])


ruleorder: filter_no_exon_overlap > process_cre
ruleorder: cre_filter_conserved > filter_enhancers
ruleorder: filter_no_exon_overlap > filter_enhancers
ruleorder: filter_no_exon_overlap > cre_filter_conserved


wildcard_constraints:
    species="|".join(SPECIES),
    dataset="|".join(DATASET_NAMES),
    intervals="|".join(ALL_INTERVALS),
    split_name="|".join(ALL_SPLIT_NAMES),
    conservation="|".join(ALL_CONSERVATIONS),
    label_type="positives|negatives|negative_candidates|negatives_gc_repeat_matched",
    neg_type="|".join(ALL_NEG_TYPES),
    n=r"\d+",
    model="|".join(MODEL_NAMES) if MODEL_NAMES else "NONE",


rule all:
    input:
        get_all_dataset_outputs(),
        [
            f"results/model/{exp['model']}/{exp['dataset']}/metrics.json"
            for exp in EXPERIMENTS
        ],
        [
            f"results/model/{exp['model']}/{exp['dataset']}/misclassified.parquet"
            for exp in EXPERIMENTS
        ],
        [
            f"results/model/{exp['model']}/{exp['dataset']}/precision_recall.parquet"
            for exp in EXPERIMENTS
        ],
        [
            f"results/visualization/{ckpt['model']}/{ckpt['dataset']}/{region['name']}.bedgraph"
            for ckpt in config.get("visualization", {}).get("checkpoints", [])
            for region in config.get("visualization", {}).get("regions", [])
        ],
