configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/data.smk"
include: "rules/model.smk"


MODEL_NAMES = list(config.get("models", {}).keys())


wildcard_constraints:
    species="|".join(SPECIES),
    dataset="|".join(DATASET_NAMES),
    intervals="|".join(ALL_INTERVALS),
    split_name="|".join(ALL_SPLIT_NAMES),
    label_type="positives|negatives",
    n=r"\d+",
    model="|".join(MODEL_NAMES) if MODEL_NAMES else "NONE",


rule all:
    input:
        get_all_dataset_outputs(),
