configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/data.smk"
include: "rules/model.smk"
include: "rules/visualization.smk"


MODEL_NAMES = [k for k in config.get("models", {}) if k != "default"]
EXPERIMENTS = config.get("experiments", [])


wildcard_constraints:
    species="|".join(SPECIES),
    dataset="|".join(DATASET_NAMES),
    intervals="|".join(ALL_INTERVALS),
    split_name="|".join(ALL_SPLIT_NAMES),
    label_type="positives|negatives",
    n=r"\d+",
    model="|".join(MODEL_NAMES) if MODEL_NAMES else "NONE",


rule all:
    input:
        get_all_dataset_outputs(),
        [
            f"results/model/{exp['model']}/{exp['dataset']}/metrics.json"
            for exp in EXPERIMENTS
        ],
        [
            f"results/visualization/{region['name']}.bedgraph"
            for region in config.get("visualization", {}).get("regions", [])
        ],
