"""Snakemake workflow: hg38↔mm10 dELS ortholog recovery via mmseqs2.

This iteration is a hello-world scoped to the ZRS limb-enhancer locus
(±100 kb in each genome). See ../README.md for context. The broader plan
(other aligners, search-space variants, conservation stratification) lives in
https://github.com/Open-Athena/bolinas-dna/issues/120.
"""


configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/download.smk"
include: "rules/extract_seqs.smk"
include: "rules/search.smk"
include: "rules/evaluate.smk"
include: "rules/sanity.smk"


rule all:
    input:
        "results/eval/per_query_report.tsv",
        "results/sanity/self_recall.parquet",
