"""Snakemake workflow: hg38↔mm10 dELS ortholog recovery via cheap pairwise aligners.

This iteration is a hello-world scoped to the ZRS limb-enhancer locus
(±100 kb on the mm10 side; hg38 side is ZRS proper). See ../README.md for
context. The broader plan (additional aligners, search-space variants,
conservation stratification) lives in
https://github.com/Open-Athena/bolinas-dna/issues/120.
"""


configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/download.smk"
include: "rules/extract_seqs.smk"
include: "rules/search.smk"
include: "rules/align_minimap2.smk"
include: "rules/align_lastz.smk"
include: "rules/evaluate.smk"
include: "rules/conservation.smk"
include: "rules/plots.smk"
include: "rules/sanity.smk"


rule all:
    input:
        expand(
            "results/eval/{aligner}/flank_{flank}/per_query_report.tsv",
            aligner=config["aligners"],
            flank=config["query_flanks_bp"],
        ),
        expand(
            "results/eval/{aligner}/flank_{flank}/recall_by_conservation/{track}.tsv",
            aligner=config["aligners"],
            flank=config["query_flanks_bp"],
            track=config["stratify_by"],
        ),
        expand(
            "results/eval/{aligner}/flank_{flank}/recall_by_class_and_conservation_fixed/{track}.tsv",
            aligner=config["aligners"],
            flank=config["query_flanks_bp"],
            track=config["stratify_by"],
        ),
        expand(
            "results/eval/{aligner}/flank_{flank}/recall_by_class_and_conservation_quantile/{track}.tsv",
            aligner=config["aligners"],
            flank=config["query_flanks_bp"],
            track=config["stratify_by"],
        ),
        expand(
            "results/plots/{aligner}/flank_{flank}/{track}_recall_heatmap.png",
            aligner=config["aligners"],
            flank=config["query_flanks_bp"],
            track=config["stratify_by"],
        ),
        expand(
            "results/plots/{aligner}/flank_{flank}/{track}_recall_curves.png",
            aligner=config["aligners"],
            flank=config["query_flanks_bp"],
            track=config["stratify_by"],
        ),
        "results/sanity/self_recall.parquet",
